[package]
name = "bevy_firebase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
prost = "0.11.9"
prost-types = "0.11.9"
serde = "1.0.164"
serde_json = "1.0.96"
url = "2.4.0"
tonic = { version = "0.9.2", features = ["tls"] }
futures-lite = "1.11.3"
bevy_macro_utils = "0.10.1"
bevy-tokio-tasks = "0.10.2"
reqwest = {version = "0.11.18", features = ["json", "multipart"]}

[build-dependencies]
tonic-build = "0.9.2"

[[example]]
name = "crud-listener"
path = "examples/crud-listener.rs"